# Generated by Django 5.2 on 2025-04-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do paciente', max_length=200, verbose_name='Nome Completo')),
                ('idade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Contato')),
                ('contapoio', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Apoio')),
                ('valor_sessao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da Sessão')),
                ('sessoes', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2, verbose_name='Quantidade de Sessões')),
                ('estrategia', models.CharField(max_length=15, verbose_name='Estratégia de venda')),
                ('preferencia', models.TextField(blank=True, max_length=2000, verbose_name='Preferências e Observações')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o paciente está ativo no sistema', verbose_name='Paciente Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
