# Generated by Django 5.2 on 2025-04-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('familia', models.CharField(max_length=200, verbose_name='Família')),
                ('email', models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Máximo de 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Decano',
                'ordering': ['nome'],
            },
        ),
    ]
