# Generated by Django 5.2 on 2025-04-24 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Contato')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Sexo')),
                ('abordagem', models.CharField(choices=[('TCC', 'Cognitivo-Comportamental'), ('PSC', 'Psicanálise'), ('HUM', 'Humanista'), ('ANA', 'Analítica')], max_length=3, verbose_name='Abordagem Terapêutica')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('nucleo', models.CharField(choices=[('Jungiano', 'Jungiano'), ('Humanista', 'Humanista'), ('Cognitivo-Comportamental', 'Cognitivo-Comportamental'), ('Neuro', 'Neuro'), ('Social', 'Social'), ('Psicanálise', 'Psicanálise'), ('Formação Clássica', 'Formação Clássica')], max_length=200, verbose_name='Núcleo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('clinica', models.CharField(choices=[('ESC', 'Clínica Escola'), ('ALL', 'Clínica Allos'), ('PAR', 'Parceria')], max_length=3, verbose_name='Clínica')),
                ('modalidade', models.CharField(choices=[('PRES', 'Presencial'), ('ONL', 'Online'), ('HIB', 'Híbrido')], max_length=4, verbose_name='Modalidade de Atendimento')),
                ('prefeidade', models.CharField(choices=[('INF', 'Infantil'), ('ADO', 'Adolescente'), ('ADU', 'Adulto'), ('IDO', 'Idoso'), ('TOD', 'Todas')], max_length=3, verbose_name='Preferência de Faixa Etária')),
                ('disponibilidade', models.TextField(blank=True, help_text='Dias e horários disponíveis para atendimento', max_length=500, verbose_name='Disponibilidade de Horários')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o terapeuta está ativo no sistema', verbose_name='Terapeuta Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('decano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeutas', to='decano.decano', verbose_name='Decano Responsável')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
                'ordering': ['nome'],
            },
        ),
    ]
