# Generated by Django 5.2 on 2025-04-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decano', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('sessao_1_realizado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_1_pago', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_2_realizado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_2_pago', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_3_realizado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_3_pago', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_4_realizado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('sessao_4_pago', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorio', to='terapeuta.terapeuta')),
                ('decano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorio', to='decano.decano')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorio', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['Terapeuta'],
            },
        ),
    ]
